# Generated by Django 5.2.10 on 2026-01-31 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_dailyreportlog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DailyReportLog',
        ),
    ]
